#==================#
#    ExPickaxes    #
#      v1.3.0      #
#   ArcticRaven_   #
#==================#

options:
	#This sets the maximum amout of blocks the pickaxes can break
	EpickMaxHealth : 1561
	
	#These set the thresholds for the notifications, by setting thier value above the EpickMaxHealth value, they will be removed
	EpickNotif1 : 1400
	EpickNotif2 : 1500
	
	#This will enable the explosion effect for ALL players, also plays the explosion sound
	ExpickEffect : true
	
command ExPick <player=%player%>:
	usage: /expick <player>
	aliases: ExPick
	permission: expick.give
	permission message: &7&l[&4&lExPick&7&l] &cYou do not have the required permission to perform this command
	trigger:
		give a diamond pickaxe with lore "&4Explosive" to arg-1	
	
on block break:
	if player have permission "epickaxe.use":
		if player is holding a diamond pickaxe with lore "&4Explosive":
			loop blocks in radius 1.75 of event-block:
				if loop-blocks are stone or cobblestone or diorite or granite or andesite or sandstone or stone bricks or netherrack or nether bricks or endstone:
					break loop-blocks naturally using player's tool
					add 1 to {uses.%player%}
					if {@ExpickEffect} is true:
						create a fake explosion at event-block
				if event-block is not stone or cobblestone or diorite or granite or andesite or sandstone or stone bricks or netherrack or nether bricks or air:
					cancel event
				if {uses.%player%} is {@EpickNotif1}:
					send action bar "&6Your Explosive Pickaxe will break soon!" to player
				if {uses.%player%} is {@EpickNotif2}:
					send action bar "&cYour Explosive Pickaxe will break very soon!" to player
				if {uses.%player%} is {@EpickMaxHealth}:
					set player's tool to air
					set {uses.%player%} to 0
					play sound "entity.item.break" with volume .75 to player
					send action bar "&4Your Explosive Pickaxe has broken!" to player
